name: CI - PHP

on:
  push:
    branches: [ "main", "developer", "teste" ]
  pull_request:
    branches: [ "main" ]

jobs:
  php-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v4.2.2

    - name: Configurar o PHP ambiente
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Verificar erros de sintaxe no PHP
      run: find . -type f -name "*.php" -not -path "*/vendor/*" -exec php -l {} \;
