name: CI - Python

on:
  push:
    branches: [ "main", "developer", "teste" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v4.2.2

    - name: Configurar o Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.14'

    - name: Instalar Todas as Dependencias do Projeto
      run: |
        python -m pip install --upgrade pip
        # Instala as ferramentas de teste
        pip install pytest pytest-mock
        # Instala absolutamente tudo o que está na sua lista do projeto
        pip install -r requirements.txt

    - name: Executar o Teste Específico das Ocorrencias
      run: pytest tests/test_report.py
