name: CI - Python

on:
  push:
    branches: [ "main", "developer", "teste" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verificar padronizacao com Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Executar testes com Pytest
      run: |
        pytest
